version: "3.4"

services:
  parser:
    build: ./
    restart: always
    environment:
      - TZ=Europe/Moscow
    ports:
      - 8085:8085
      - 8084:8084

  swagger:
    env_file: .env
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - 8083:8080
    environment:
      - SWAGGER_JSON=docs/parser.swagger.json


